---
title: "Bug Kids"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r packages, echo = FALSE}
library(vegan)
library(ggplot2)
library(tidyr)
library(plyr)
library(mgcv)
library(randomForest)
require(caTools)
library(reshape2)

#source('C:/Users/jeffr/Documents/School/MATH 6315/traditionalForwardBackward_lm.R')
#source('C:/Users/jeffr/Documents/School/MATH 6315/diagPlots.R')
#source('C:/Users/jeffr/Documents/School/MATH 6315/augPairs.R')

```

``` {}

df1 <- read.csv("pan_fix.csv")
  
df2 <- read.csv("sweep_fix.csv")
  
df3 <- read.csv("vegetationdata_updatedtest.csv")

panmarsh <- df1[df1$Strata == "J",]

panNC <- df1[df1$Strata == "NC",]

panHP <- df1[df1$Strata == "HP",]

sweepjuncus <- df2[df2$Strata == "J",]

sweepNC <- df2[df2$Strata == "NC",]

sweepHP <- df2[df2$Strata == "HP",]

plantmarsh <- df3[df3$Strata == "J",]

plantNC <- df3[df3$Strata == "NC",]

plantHP <- df3[df3$Strata == "HP",]


```

## Including Plots

You can also embed plots, for example:

```{r rarefaction setup, echo=FALSE}

juncuspmat <- as.matrix(panmarsh[,5:13])

NCpmat <- as.matrix(panNC[,5:13])

HPpmat <- as.matrix(panHP[,5:13])

juncussmat <- as.matrix(sweepjuncus[,5:12])

NCsmat <- as.matrix(sweepNC[,5:12])

HPsmat <- as.matrix(sweepHP[,5:12])

juncusplmat <- as.matrix(plantmarsh[,4:12])

NCplmat <- as.matrix(plantNC[,4:12])

HPplmat <- as.matrix(plantHP[,4:12])

```

```{r rarefaction plots}

juncusprar<- specaccum(juncuspmat, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")
NCprar<- specaccum(NCpmat, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")
HPprar<- specaccum(HPpmat, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")

plot(juncusprar, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "orange", ci.lty = 1, lwd= 3.5, xlim = c(1,10),
     ylim = c(1,9), xlab = "YPT Sets", ylab = "Orders")
par(new = TRUE)
plot(NCprar, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "blue", ci.lty = 1, lwd= 3.5, xlim = c(1,10), 
     ylim = c(1,9), xlab = "YPT Sets", ylab = "Orders")
par(new = TRUE)
plot(HPprar, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "green", ci.lty = 1, lwd= 3.5, xlim = c(1,10), 
     ylim = c(1,9), xlab = "YPT Sets", ylab = "Orders")
legend("topleft", legend = c("orange - Juncus", "blue - Near Creek", "green - Hodgepodge"))

juncusrar<- specaccum(juncussmat, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")
NCsrar<- specaccum(NCsmat, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")
HPsrar<- specaccum(HPsmat, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")

plot(juncusrar, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "orange", ci.lty = 1, lwd= 3.5, xlim = c(1,10),
     ylim = c(1,10), xlab = "Sweep Survey", ylab = "Orders")
par(new = TRUE)
plot(NCsrar, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "blue", ci.lty = 1, lwd= 3.5, xlim = c(1,10), 
     ylim = c(1,10), xlab = "Sweep Survey", ylab = "Orders")
par(new = TRUE)
plot(HPsrar, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "green", ci.lty = 1, lwd= 3.5, xlim = c(1,10), 
     ylim = c(1,10), xlab = "Sweep Survey", ylab = "Orders")
legend("topleft", legend = c("orange - Juncus", "blue - Near Creek", "green - Hodgepodge"))

juncusplrar<- specaccum(juncusplmat, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")
NCplrar<- specaccum(NCplmat, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")
HPplrar<- specaccum(HPplmat, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")

plot(juncusplrar, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "orange", ci.lty = 1, lwd= 3.5, xlim = c(1,10),
     ylim = c(1,8), xlab = "Plant Survey", ylab = "Species")
par(new = TRUE)
plot(NCplrar, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "blue", ci.lty = 1, lwd= 3.5, xlim = c(1,10), 
     ylim = c(1,8), xlab = "Plant Survey", ylab = "Species")
par(new = TRUE)
plot(HPplrar, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "green", ci.lty = 1, lwd= 3.5, xlim = c(1,10), 
     ylim = c(1,8), xlab = "Plant Survey", ylab = "Species")
legend("topleft", legend = c("orange - Juncus", "blue - Near Creek", "green - Hodgepodge"))
```

rarefaction by site

```{r}
pan2007 <- df1[df1$Site == "2007",]

pan2013 <- df1[df1$Site == "2013",]

pan2015 <- df1[df1$Site == "2015",]

sweep2007 <- df2[df2$Site == "2007",]

sweep2013 <- df2[df2$Site == "2013",]

sweep2015 <- df2[df2$Site == "2015",]

plant2007 <- df3[df3$site == "2007",]

plant2013 <- df3[df3$site == "2013",]

plant2015 <- df3[df3$site == "2015",]

```

```{r}
pmat2007 <- as.matrix(pan2007[,5:13])

pmat2013 <- as.matrix(pan2013[,5:13])

pmat2015 <- as.matrix(pan2015[,5:13])

smat2007 <- as.matrix(sweep2007[,5:12])

smat2013 <- as.matrix(sweep2013[,5:12])

smat2015 <- as.matrix(sweep2015[,5:12])

plmat2007 <- as.matrix(plant2007[,4:12])

plmat2013 <- as.matrix(plant2013[,4:12])

plmat2015 <- as.matrix(plant2015[,4:12])
```


```{r rarefaction plots}

prar2007<- specaccum(pmat2007, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")
prar2013<- specaccum(pmat2013, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")
prar2015<- specaccum(pmat2015, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")

plot(prar2007, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "orange", ci.lty = 1, lwd= 3.5, xlim = c(1,10),
     ylim = c(1,9), xlab = "YPT Sets", ylab = "Orders")
par(new = TRUE)
plot(prar2013, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "blue", ci.lty = 1, lwd= 3.5, xlim = c(1,10), 
     ylim = c(1,9), xlab = "YPT Sets", ylab = "Orders")
par(new = TRUE)
plot(prar2015, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "green", ci.lty = 1, lwd= 3.5, xlim = c(1,10), 
     ylim = c(1,9), xlab = "YPT Sets", ylab = "Orders")
legend("topleft", legend = c("orange - 2007", "blue - 2013", "green - 2015"))

srar2007<- specaccum(smat2007, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")
srar2013<- specaccum(smat2013, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")
srar2015<- specaccum(smat2015, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")

plot(srar2007, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "orange", ci.lty = 1, lwd= 3.5, xlim = c(1,10),
     ylim = c(1,10), xlab = "Sweep Survey", ylab = "Orders")
par(new = TRUE)
plot(srar2013, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "blue", ci.lty = 1, lwd= 3.5, xlim = c(1,10), 
     ylim = c(1,10), xlab = "Sweep Survey", ylab = "Orders")
par(new = TRUE)
plot(srar2015, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "green", ci.lty = 1, lwd= 3.5, xlim = c(1,10), 
     ylim = c(1,10), xlab = "Sweep Survey", ylab = "Orders")
legend("topleft", legend = c("orange - 2007", "blue - 2013", "green - 2015"))

plrar2007<- specaccum(plmat2007, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")
plrar2013<- specaccum(plmat2013, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")
plrar2015<- specaccum(plmat2015, method = "random", permutations = 999, conditioned = TRUE, gamma = "jack1")

plot(plrar2007, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "orange", ci.lty = 1, lwd= 3.5, xlim = c(1,10),
     ylim = c(1,8), xlab = "Plant Survey", ylab = "Species")
par(new = TRUE)
plot(plrar2013, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "blue", ci.lty = 1, lwd= 3.5, xlim = c(1,10), 
     ylim = c(1,8), xlab = "Plant Survey", ylab = "Species")
par(new = TRUE)
plot(plrar2015, add = FALSE, ci = 1, ci.type = c("bar", "line", "polygon"), 
     col = par("fg"), ci.col = "green", ci.lty = 1, lwd= 3.5, xlim = c(1,10), 
     ylim = c(1,8), xlab = "Plant Survey", ylab = "Species")
legend("topleft", legend = c("orange - 2007", "blue - 2013", "green - 2015"))
```


```{r one-way PERMANOVA setup, echo=FALSE}

df1<-na.omit(df1)

pan<-as.matrix(df1[,5:13])
panMETA<-df1[,c(1:4)]
##habitat.sqrt<-sqrt(habitat) #square root transform
pan.dist<-vegdist(pan, method='bray', na.rm = TRUE) #Bray-curtis dissimilarity matrix

df2<-na.omit(df2)

sweep<-as.matrix(df2[,5:12])
##habitat.sqrt<-sqrt(habitat) #square root transform
sweep.dist<-vegdist(sweep, method='bray', na.rm = TRUE) #Bray-curtis dissimilarity matrix

df3<-na.omit(df3)
## check/fix!!

plant<-as.matrix(df3[,4:12])
plantMETA<-df3[,c(1:3)]
##habitat.sqrt<-sqrt(habitat) #square root transform
plant.dist<-vegdist(plant, method='bray', na.rm = TRUE) #Bray-curtis dissimilarity matrix
```

```{r dispersion, echo = FALSE}

pan.dispersion <- betadisper(pan.dist, group=df1$Strata)
permutest(pan.dispersion)
plot(pan.dispersion, hull=FALSE, ellipse=TRUE)

sweep.dispersion <- betadisper(sweep.dist, group=df2$Strata)
permutest(sweep.dispersion)
plot(sweep.dispersion, hull=FALSE, ellipse=TRUE)

plant.dispersion <- betadisper(plant.dist, group=df3$Strata)
permutest(plant.dispersion)
plot(plant.dispersion, hull=FALSE, ellipse=TRUE)
```

```{r one-way PERMANOVA all nekton}
panPERM<-adonis2(pan.dist~Strata, data=df1, permutations = 999, method = "bray", strata="PLOT")
panPERM

simper_pan<-simper(pan, panMETA$Strata, permutations = 999)
summary(simper_pan, ordered=TRUE, digits=max(3))

sweepPERM<-adonis2(sweep.dist~Strata, data=df2, permutations = 999, method = "bray", strata="PLOT")
sweepPERM

plantPERM<-adonis2(plant.dist~site, data=df3, permutations = 999, method = "bray", strata="PLOT")
plantPERM

simper_plant<-simper(plant, plantMETA$site, permutations = 999)
summary(simper_plant, ordered=TRUE, digits=max(3))

```
```{r one-way PERMANOVA most abundant, echo=FALSE}
# skip this part?
df3<-na.omit(df3)

habitat<-as.matrix(df3[,16:42])
habitat.sqrt<-sqrt(habitat) #square root transform
habitat.dist<-vegdist(habitat.sqrt, method='bray', na.rm = TRUE) #Bray-curtis dissimilarity matrix

habitatPERM<-adonis2(habitat.dist~habitat, data=df2, permutations = 999, method = "bray", strata="PLOT")
habitatPERM

habitatMETA<-df3[,c(1:15)]

simper_habitat<-simper(habitat, habitatMETA$habitat, permutations = 999)
summary(simper_habitat, ordered=TRUE, digits=max(3))

```

```{r}
pan2007 <- df1 %>% filter(Site == "2007")

pan2013 <- df1 %>% filter(Site == "2013")

pan2015 <- df1 %>% filter(Site == "2015")

mat2007 <- as.matrix(pan2007[,5:13])

mat2013 <- as.matrix(pan2013[,5:13])

mat2015 <- as.matrix(pan2015[,5:13])

sw.div2007 = mean(diversity(mat2007, index = "shannon"))
sd(diversity(mat2007, index = "shannon"))

sw.div2013 = mean(diversity(mat2013, index = "shannon"))
sd(diversity(mat2013, index = "shannon"))

sw.div2015 = mean(diversity(mat2015, index = "shannon"))
sd(diversity(mat2015, index = "shannon"))
```

```{r}

```

